import express from 'express';
const app = express();
import http from 'http';
const server = http.createServer(app);

import leaderBoardRoute from './leaderboard.js';
import authRoute from './auth.js';

import Game from "./refactored_game.js";
import { addGameWon, addGamePlayed } from './dbUtils.js';

/*
Have a map structure that maps the "Game-ID" to the two players + physics engine
Better experience only two players to a game.

Game-ID will be generated by 
*/
// Allows for client to connect while orignally @ localhost:3000 or else CORS errors
const PORT = 5500;

app.use(express.json());

app.use('/api/leaderboard', leaderBoardRoute);
app.use('/api/', authRoute);
app.use(express.static('public'));
const game = new Game(server);
server.listen(PORT, () => {
    console.log(`Listening on port ${PORT}`);
});